[project]
name = "cmdstan_update"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "5.4.0"

[tasks]

[dependencies]
pandas = ">=2.2.3,<2.3"
polars = ">=1.9.0,<1.10"
numpy = ">=2.1.2,<2.2"
scipy = ">=1.14.1,<1.15"
matplotlib = ">=3.9.2,<3.10"
seaborn = ">=0.13.2,<0.14"
arviz = ">=0.20.0,<0.21"
cmdstan = ">=2.35.0,<2.36"
cmdstanpy = ">=1.2.4,<1.3"

[pypi-dependencies]

[feature.dev.dependencies]
pytest = ">=8.3.3,<8.4"

[environments]
default = { features = ["dev"], solve-group = "prod" }
prod = { features = [], solve-group = "prod" }
